import { BookOpenCheck, CalendarCheck2, MessagesSquare, Network } from 'lucide-react'
import type { Blueprint } from '../types'

export const blueprints: Blueprint[] = [
  {
    slug: 'ai-customer-support-system',
    category: 'Customer Experience',
    title: 'AI Customer Support System',
    problem: 'Support teams repeatedly answer the same questions across website, email, and messaging channels.',
    solution: 'A knowledge-grounded AI assistant that handles common requests, captures context, escalates complex issues, and keeps conversations organized.',
    workflow: [
      { label: 'Customer question' },
      { label: 'Knowledge retrieval' },
      { label: 'AI response' },
      { label: 'Confidence check' },
      { label: 'Human escalation' },
    ],
    integrations: ['Website', 'WhatsApp', 'Email', 'Knowledge Base', 'CRM'],
    impactLabel: 'Potential value',
    impact: 'Faster first responses and reduced repetitive support workload.',
    icon: MessagesSquare,
    accent: 'violet',
  },
  {
    slug: 'ai-appointment-booking-system',
    category: 'Service Operations',
    title: 'AI Appointment & Booking System',
    problem: 'Manual scheduling creates delays, missed inquiries, double bookings, and unnecessary administrative work.',
    solution: 'An intelligent booking assistant that checks availability, collects required details, schedules appointments, and sends reminders.',
    workflow: [
      { label: 'New inquiry' },
      { label: 'Service selection' },
      { label: 'Availability check' },
      { label: 'Booking confirmation' },
      { label: 'Reminder sequence' },
    ],
    integrations: ['Website', 'Google Calendar', 'Email', 'WhatsApp', 'CRM'],
    impactLabel: 'Potential value',
    impact: 'Fewer scheduling delays and a smoother customer booking experience.',
    icon: CalendarCheck2,
    accent: 'cyan',
  },
  {
    slug: 'ai-internal-knowledge-assistant',
    category: 'Team Productivity',
    title: 'AI Internal Knowledge Assistant',
    problem: 'Employees lose time searching through documents, policies, files, and scattered internal information.',
    solution: 'A secure internal assistant that retrieves approved company knowledge and gives concise, source-grounded answers.',
    workflow: [
      { label: 'Team question' },
      { label: 'Permission check' },
      { label: 'Knowledge search' },
      { label: 'Grounded answer' },
      { label: 'Source references' },
    ],
    integrations: ['Google Drive', 'Notion', 'Slack', 'Internal Docs', 'Help Center'],
    impactLabel: 'Potential value',
    impact: 'Faster access to internal knowledge and fewer repeated questions across teams.',
    icon: BookOpenCheck,
    accent: 'emerald',
  },
  {
    slug: 'ai-operations-automation',
    category: 'Business Operations',
    title: 'AI Operations Automation',
    problem: 'Business data is manually copied between forms, spreadsheets, CRM systems, email, and messaging tools.',
    solution: 'An automated operations layer that validates information, updates connected systems, triggers actions, and flags exceptions.',
    workflow: [
      { label: 'Data received' },
      { label: 'Validation' },
      { label: 'AI classification' },
      { label: 'System update' },
      { label: 'Team notification' },
    ],
    integrations: ['Forms', 'Google Sheets', 'CRM', 'Email', 'Slack'],
    impactLabel: 'Potential value',
    impact: 'Less manual data handling, fewer process errors, and faster internal execution.',
    icon: Network,
    accent: 'indigo',
  },
]
